apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    apps: test
spec:
  type: NodePort
  ports:
  - name: web-port service
    nodePort: 31081
    port: 5000
    protocol: TCP
  selector:
    app: test
