apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-app
        image: avinashdere99/python:tag
        env:
        - name: MONGODB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongodb_configmap
              key: database_url
        ports:
        - containerPort: 5000
          name: web-port
